oifits
Bottleneck>=1.3.2
PyYAML
aplpy >= 2.0.3
asdf==2.7.1
astrocut>=0.5
astrodendro==0.2.0
astropy
astroquery
corner >= 2.0.1
dill==0.3.1.1
dust-extinction==0.8
emcee==3.0.2
glue-astronomy==0.1
glue-core==1.0.0
glue-jupyter==0.2.1
glue-vispy-viewers==1.0.1
gwcs>=0.11.0
h5py==2.10.0
healpy>=1.12.5
ipyvue>=1.3.4
ipyvuetify>=1.4.1
ipywidgets
joblib==0.14.1
juliet >= 2.0.25
jupyter
jwst
lmfit==0.9.13
matplotlib
mplcursors
munch
notebook==6.1.5
numpy
numpymatplotlib==3.2.1
pandas==1.1.2
photutils==1.0.1
poppy
pysiaf==0.9.0
pysynphot==1.0.0
pyyaml>=5.3.1
scikit-image
scipy
seaborn >= 0.9.0
shapely>=1.7.0
spectral-cube >= 0.4.0
specutils
termcolor
uncertainties
webbpsf
git+https://github.com/astropy/regions.git
git+https://github.com/radio-astro-tools/radio-beam.git
git+https://github.com/spacetelescope/jdaviz.git@625acca8562249c2f4d9041c566c1820a4d480b2#egg=jdaviz
git+https://github.com/spacetelescope/jwst@0.17.0#egg=jwst
git+https://github.com/spacetelescope/jwst_gtvt.git
git+https://github.com/spacetelescope/mirage#egg=mirage
