name: test-markdown
on: [push]

jobs:
  build:
    name: autopy-lot-md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: autopy-lot 
        uses: deep5050/autopy-lot@master
          check:
          input_type:
          comment_magics:
          split_at_heading:
          output_type:
          output_dir: '/notebooks/'
          output_type: markdown
