name: Test-Notebooks

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  test-notebooks:
    # Name the job
    name: Test Jupyter Notebooks
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jupyter-actions
          environment-file: environment.yml
          python-version: 3.7

      - name: Execute all Notebooks
        shell: bash -l {0}
        run: |
          conda activate jupyter-actions
          pytest
          
      - name: Install nbconvert
        run: pip install nbconvert
        
      - name: Install jupyter
        run:  pip install jupyter
        
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Convert all ipynb files to html (and delete ipynb files)
        run: jupyter nbconvert --template classic --to html --execute --EmbedImagesPreprocessor.embed_images=True

      - name: Push notebooks folder to the build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: notebooks # The directory where your assets are generated
          BRANCH: build # The branch name where you want to push the assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          SQUASH_HISTORY: true # If set to true, all previous commits on the target branch will be discarded. For example, if you are deploying a static site with lots of binary artifacts, this can help the repository becoming overly bloated.
